output "client_key" {
  description = "Raw Kubernetes config to be used by kubectl"
  value     = module.jenkins_k8cluster.client_key
  sensitive = true
}

output "client_certificate" {
  description = "Base64 encoded public certificate used by clients to authenticate to the Kubernetes cluster"
  value     = module.jenkins_k8cluster.client_certificate
  sensitive = true
}

output "cluster_ca_certificate" {
  description = "Base64 encoded public CA certificate used as the root of trust for the Kubernetes cluster."
  value     = module.jenkins_k8cluster.cluster_ca_certificate
  sensitive = true
}

output "cluster_username" {
  description = "A username used to authenticate to the Kubernetes cluster."
  value = module.jenkins_k8cluster.username
}

output "cluster_password" {
  description = "A password or token used to authenticate to the Kubernetes cluster."
  value     = module.jenkins_k8cluster.password
  sensitive = true
}

output "kube_config_raw" {
  description = "Raw Kubernetes config to be used by kubectl"
  value     = module.jenkins_k8cluster.kube_config_raw
  sensitive = true
}

output "kube_config" {
  description = "Kubernetes config"
  value     = module.jenkins_k8cluster.kube_config
  sensitive = true
}

output "host" {
  description = "The Kubernetes cluster server host."
  value = module.jenkins_k8cluster.host
}

output "private_fqdn" {
  description = "The Kubernetes Managed Cluster ID"
  value = module.jenkins_k8cluster.private_fqdn
}

output "sp_object_id" {
  description = "The Service Principal Object ID"
  value = module.jenkins_k8cluster.service_principal_object_id
}

output "jenkins_cluster_id" {
  description = "The Kubernetes Managed Cluster ID"
  value       = module.jenkins_k8cluster.id
}

output "managed_rg_name" {
  description = "Resource Group name managed by Microsoft when creating the cluster"
  value       = module.jenkins_k8cluster.managed_rg_name
}

output "private_dns_zone_name" {
  description = "Zone Name for the Private DNS Zone generated by private AKS"
  value       = module.jenkins_k8cluster.private_dns_zone_name
}

output "private_dns_zone_id" {
  description = "The ID of the Private DNS Zone Virtual Network Link"
  value       = module.jenkins_k8cluster.private_dns_zone_id
}

output "jenkins-password" {
  sensitive = true
  value = random_password.password.result
}

output "jenkins-user" {
  value = var.jenkins-admin-user
}