output "client_key" {
  value     = module.jenkins_k8cluster.client_key
  sensitive = true
}

output "client_certificate" {
  value     = module.jenkins_k8cluster.client_certificate
  sensitive = true
}

output "cluster_ca_certificate" {
  value     = module.jenkins_k8cluster.cluster_ca_certificate
  sensitive = true
}

output "cluster_username" {
  value = module.jenkins_k8cluster.username
}

output "cluster_password" {
  value     = module.jenkins_k8cluster.password
  sensitive = true
}

output "kube_config_raw" {
  value     = module.jenkins_k8cluster.kube_config_raw
  sensitive = true
}

output "kube_config" {
  value     = module.jenkins_k8cluster.kube_config
  sensitive = true
}

output "host" {
  value = module.jenkins_k8cluster.host
}

output "private_fqdn" {
  value = module.jenkins_k8cluster.private_fqdn
}

output "jenkins_cluster_id" {
  description = "The Kubernetes Managed Cluster ID"
  value       = module.jenkins_k8cluster.id
}

output "managed_rg_name" {
  description = "Resource Group name managed by Microsoft when creating the cluster"
  value       = module.jenkins_k8cluster.managed_rg_name
}

output "private_dns_zone_name" {
  value       = module.jenkins_k8cluster.private_dns_zone_name
  description = "Zone Name for the Private DNS Zone generated by private AKS"
}

output "private_dns_zone_id" {
  value       = module.jenkins_k8cluster.private_dns_zone_id
  description = "The ID of the Private DNS Zone Virtual Network Link"
}

output "jenkins-password" {
  value = random_password.password.result
}

output "jenkins-user" {
  value = var.jenkins-admin-user
}