output "client_key" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.client_key
  sensitive   = true
}

output "client_certificate" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.client_certificate
  sensitive   = true
}

output "cluster_ca_certificate" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.cluster_ca_certificate
  sensitive   = true
}

output "cluster_username" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.username
}

output "cluster_password" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.password
  sensitive   = true
}

output "kube_config" {
  value = azurerm_kubernetes_cluster.k8s.kube_config_raw
}

output "host" {
  value = azurerm_kubernetes_cluster.k8s.kube_config.0.host
}

/* output "id" {
  description = "The Kubernetes Managed Cluster ID"
  value       = module.jenkins_k8cluster.id
}

output "kube_config" {
  value     = module.jenkins_k8cluster.kube_config
  sensitive = true
}

output "private_fqdn" {
  value = module.jenkins_k8cluster.private_fqdn
}

output "client_key" {
  value     = module.jenkins_k8cluster.client_key
  sensitive = true
}

output "client_certificate" {
  value     = module.jenkins_k8cluster.client_certificate
  sensitive = true
}

output "cluster_ca_certificate" {
  value     = module.jenkins_k8cluster.cluster_ca_certificate
  sensitive = true
}

output "cluster_username" {
  value = module.jenkins_k8cluster.username
}

output "cluster_password" {
  value     = module.jenkins_k8cluster.password
  sensitive = true
}

output "host" {
  value = module.jenkins_k8cluster.host
}

output "managed_rg_name" {
  value       = module.jenkins_k8cluster.managed_rg_name
  description = "Resource Group name managed by Microsoft when creating the cluster"
}

output "private_dns_zone_name" {
  value       = module.jenkins_k8cluster.private_dns_zone_name
  description = "Zone Name for the Private DNS Zone generated by private AKS"
}

output "private_dns_zone_id" {
  value       = module.jenkins_k8cluster.private_dns_zone_id
  description = "The ID of the Private DNS Zone Virtual Network Link"
}

output "chart" {
  value       = module.jenkins_k8cluster.chart
  description = "The name of the chart"
} */

output "managed_disk_id" {
  value       = azurerm_managed_disk.jenkins_managed_disk.id
  description = "The ID of the Managed Disk."
}

/* output "jenkins_k8s_self_link" {
  value       = kubernetes_secret.jenkins_k8secret.self_link
  description = "A URL representing this secret."
}

output "jenkins_k8s_uid" {
  value       = kubernetes_secret.jenkins_k8secret.uid
  description = "The unique in time and space value for this secret."
} */

/* output "jenkins_k8s_secret_module" {
  value       = kubernetes_secret.jenkins_k8secret
} */